#!/usr/bin/env bash
# This script has 2 if statements

i=1

while [ $i -le 10 ]
do
	if [ $i = 4 ]
	then
		echo "bad luck"
	elif [ $i = 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done

