#!/usr/bin/env bash
# This changes the ip routes of 2 domains
sudo cp /etc/hosts ~/hosts.new
sudo sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new
echo "8.8.8.8	facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
